### ISSUE TITLE
ClockVector increasing due to un-applied patches

### ISSUE THREAD

**Issue by Chandelier-02** [streamich/json-joy#685]
Hi, I have been experimenting around with the JSON-JOY CRDT library and have been trying to implement a sync mechanism for the patches. I noticed some behavior that seemed weird to me. Whenever I create a document and perform some operations, I gather each operation as its own patch. I plan to use these patches to reconstruct a new document. I noticed that when I apply patch 0, 1, 2, 3, and then patch 20, patch 20 doesn't get applied (expected), but the ClockVector does get incremented to that last patch's clock value (20). This creates some weird behavior when I am trying to sync documents as I look at their state vectors to know which patches I need to send over the network. In the example above, I would assume that the document created from the patches would be caught up even if it was missing the majority of its patches. I would expect the ClockVector to only show the max updates that have been applied per session id. 

I tried performing the same test with yjs and it worked as I expected. 
I am not  CRDT expert, so I may be missing something, but I just thought it would be good to bring it up. Maybe I am doing something wrong in the test?

Here is the code to reproduce:
```
const jsonJoyStateVectorTest = () => {
  const schema = s.obj({
    arr: s.arr([]),
  });
  const jsonJoyDoc = Model.create(schema);
  console.log(jsonJoyDoc.clock.sid);
  const updates: Uint8Array[] = [];

  jsonJoyDoc.api.builder.patch.ops.map(op => console.log(op.toString() + '\n'));
  const patch = jsonJoyDoc.api.flush();

  updates.push(patch.toBinary());

  const arrApi = jsonJoyDoc.api.arr('arr');
  for (let i = 0; i < 10; i++) {
    arrApi.ins(i, [i]);
    jsonJoyDoc.api.builder.patch.ops.map(op => console.log(op.toString() + '\n'));

    const patch = arrApi.api.flush();
    updates.push(patch.toBinary());
  }

  console.log(jsonJoyDoc + '');
  console.log(jsonJoyDoc.clock);

  const jsonJoyDoc2 = Model.create(schema);
  jsonJoyDoc.applyPatch(Patch.fromBinary(updates[0]));
  jsonJoyDoc2.applyPatch(Patch.fromBinary(updates[1]));
  jsonJoyDoc2.applyPatch(Patch.fromBinary(updates[2]));
  jsonJoyDoc2.applyPatch(Patch.fromBinary(updates[3]));
  jsonJoyDoc2.applyPatch(Patch.fromBinary(updates[9]));

  console.log(jsonJoyDoc2 + '');
  console.log(jsonJoyDoc2.clock);
};
```

**Comment by streamich** [comment]
The reason is that the last change `updates[9]` is not visible, is because you are not applying the patches it depends on (4, 5, 6, 7, 8).

While the patches can be applied in different order from different users. The patches from the same user (same `sid`) should be all applied in order. That is should be easy to enforce in any environment (peer-to-peer or with central server).

Y.js should have the same restriction. This specific example might work in Y.js because you are inserting at the end of the array, and it keep the *right-reference* to the end of the array. If you inserted in the middle of some text, I expect that gaps in operations would make the last operation invisible in Y.js, too.

([I've reposted your code snippet in this Replit](https://replit.com/@streamich/issues685#index.js).)
